<?xml version="1.0"?>
<!-- 摄像头相关的 xacro 文件 -->
<robot name="CAMERA" xmlns:xacro="http://wiki.ros.org/xacro">
  <!-- 摄像头属性 -->
  <xacro:property name="camera_length" value="0.025" /> <!-- 摄像头长度(x) -->
  <xacro:property name="camera_width" value="0.025" /> <!-- 摄像头宽度(y) -->
  <xacro:property name="camera_height" value="0.025" /> <!-- 摄像头高度(z) -->
  <xacro:property name="camera_x" value="0.08" /> <!-- 摄像头安装的x坐标 -->
  <xacro:property name="camera_y" value="0.0" /> <!-- 摄像头安装的y坐标 -->
  <xacro:property name="M_PI" value="3.14159" /> <!-- 摄像头安装的y坐标 -->
  <xacro:property name="camera_z" value="${base_link_length / 2 + camera_height / 2}" /> <!--
  摄像头安装的z坐标:底盘高度 / 2 + 摄像头高度 / 2  -->

  <xacro:property name="camera_m" value="0.01" /> <!-- 摄像头质量 -->

  <xacro:macro name="Box_inertial_matrix" params="m l w h">
    <inertial>
      <mass value="${m}" />
      <inertia ixx="${m*(h*h + l*l)/12}" ixy="0" ixz="0"
        iyy="${m*(w*w + l*l)/12}" iyz="0"
        izz="${m*(w*w + h*h)/12}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="gazebo_ros_kinect_camera" params="camera_name:=camera frame_name:=camera">
     <gazebo reference="camera">  
      <sensor type="depth" name="camera">
        <always_on>true</always_on>
        <update_rate>30.0</update_rate>
        <camera>
          <horizontal_fov>${60.0*M_PI/180.0}</horizontal_fov>
          <image>
            <format>R8G8B8</format>
            <width>1280</width>
            <height>720</height>
          </image>
          <clip>
            <near>0.05</near>
            <far>8.0</far>
          </clip>
        </camera>
        <plugin name="kinect_camera_controller" filename="libgazebo_ros_openni_kinect.so">
          <cameraName>/camera</cameraName>
          <alwaysOn>true</alwaysOn>
          <updateRate>10</updateRate>
          <imageTopicName>rgb/image_raw</imageTopicName>
          <depthImageTopicName>depth/image_raw</depthImageTopicName>
          <pointCloudTopicName>depth/points</pointCloudTopicName>
          <cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>
          <depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>
          <frameName>camera</frameName>
          <baseline>0.1</baseline>
          <distortion_k1>0.0</distortion_k1>
          <distortion_k2>0.0</distortion_k2>
          <distortion_k3>0.0</distortion_k3>
          <distortion_t1>0.0</distortion_t1>
          <distortion_t2>0.0</distortion_t2>
          <pointCloudCutoff>0.4</pointCloudCutoff>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>


  <xacro:macro name="camera_sensor" params="name:=camera parentLink:=oasis_300">
    <link name="${name}">
    <visual>
      <geometry>
        <box size="${camera_length} ${camera_width} ${camera_height}" />
      </geometry>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
    </visual>
    <collision>
      <geometry>
        <box size="${camera_length} ${camera_width} ${camera_height}" />
      </geometry>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
    </collision>
    <xacro:Box_inertial_matrix m="${camera_m}" l="${camera_length}" w="${camera_width}"
      h="${camera_height}" />
    </link>
  <joint name="camera2oasis_300" type="fixed">
    <parent link="${parentLink}" />
    <child link="${name}" />
    <origin rpy="0 0 ${M_PI}" xyz="-0.48 0.08 0.045"/>
  </joint>
    <xacro:gazebo_ros_kinect_camera />
     <gazebo reference="camera">
        <material>Gazebo/Blue</material>
    </gazebo>
  </xacro:macro>



</robot>